### ISSUE TITLE
[BUG] 暗黑模式主题主色下Table下的表格分组分组行仍然是亮色

### ISSUE THREAD

**Issue by Memoyu** [DouyinFE/semi-design#2144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

table

### Semi Version

2.54.1

### Current Behavior

亮色模式下：
![image](https://github.com/DouyinFE/semi-design/assets/33112476/8b5080da-c790-4fb9-aa5a-24a8bae1cfcf)
暗色模式下：
![image](https://github.com/DouyinFE/semi-design/assets/33112476/25e10e18-cf76-4bfd-bc85-a5698ffb9cb5)

### Expected Behavior

希望暗色模式下能匹配暗色

### Environment

```markdown
- OS:windows
- browser:edge
```

**Comment by Memoyu** [comment]
![image](https://github.com/DouyinFE/semi-design/assets/33112476/fcc3f69b-6f2b-4753-8442-730f9fcf52a3)
目前的临时解决方案
```css
.semi-table-row-section {
    background-color: var(--semi-color-fill-0);
}
.semi-table-row-cell {
    background-color: transparent !important;
}
```
