### ISSUE TITLE
[BUG] 优化存在边框的 Input Group 的显示样式

### ISSUE THREAD

**Issue by ilxqx** [DouyinFE/semi-design#2445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Input

### Semi Version

2.64

### Current Behavior

不好描述，截图如下：
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/7ddb7ba5-d9a6-4848-a823-800dc3cbf455">
另外一张：
<img width="661" alt="image" src="https://github.com/user-attachments/assets/d9d561aa-c33a-428a-99eb-173cbc54219f">

可以看到，里面的输入框组中间的边框重叠了，看着很是难受

### Expected Behavior

边框重叠的时候只显示一个边框

### Steps To Reproduce

用主题设计系统，将输入框、下拉选择框等等类似输入框的组件的边框全放出来（设置好几个对应的css变量或scss变量）

### Environment

```markdown
- OS: 最新MacOS
- browser: 最新Chrome
```

### Anything else?

难怪我看官网组件库默认的主题中类似输入框的组件都是没有边框的，靠着灰色背景识别各种输入或选择框，难道是因为边框的重叠线不好处理吗？
我们是在不是很喜欢这种默认没有边框（Border）的类似输入框的各种组件，于是我就通过主题定制系统，克隆了一份飞书的主题然后自己改，结果边框的这个问题还挺头大的，不知道官方是否可以解决此问题呢？既然可以通过主题定制系统，那理论上应该考虑通过主题定制出来的系统也可以完美运作呢。

**Comment by ilxqx** [comment]
我截一张更清楚的图：
<img width="498" alt="image" src="https://github.com/user-attachments/assets/27d3ce49-3b51-4042-becf-1d8df3e24f79">

**Comment by YannLynn** [comment]
@DaiQiangReal  康康这个问题

**Comment by linpan** [comment]
> @DaiQiangReal 康康这个问题

问题很多，跟不上队伍， 会淘汰

**Comment by linpan** [comment]
> 可以先覆盖 css 解决下，dsm 其实有可以自定义 css 的功能，但是是灰度放开的，你可以先在本地项目里覆盖下这里的 边框

怎么覆盖 token。

**Comment by ilxqx** [comment]
> Semi 的风格就是整体面性的，不用边框是因为边框太丑了。不过这里的token 缺少确实可以放出来，不然用户不好处理这个情况。但是就算放出来，也很难通过配置 token 的值来让inputGroup 的时候的右侧边框消失

边框丑与不丑实属仁者见仁智者见智的问题，我倒是建议官方可以将输入框类型的组件增加个 Prop  variant（取值：borderless, solid, underline, fill 等）来控制要不要显示边框，如果显示边框怎么显示，下划线还是没有边框亦或是现在这种填充个灰背景... 这样我觉得更好呢。

**Comment by SudoUserReal** [comment]
感谢反馈，问题描述很清晰。

确实，当前 InputGroup 在子组件有边框的情况下会出现边框重叠的问题。我们在设计时主要考虑的是 Semi 默认的无边框风格，对自定义边框场景的支持确实不够完善。

后续计划增加一个 `borderCollapse` 属性来解决这个问题：
- 开启后会移除 InputGroup 内部的分隔线
- 相邻子组件的边框会合并为一条
- 支持 hover、focus 等状态的正常表现

不过考虑到这个改动会影响现有用户的预期行为，我们会放在下个 major 版本中发布。在此期间，如果急需解决，可以先通过覆盖 CSS 的方式临时处理：

```css
/* 隐藏 InputGroup 内的分隔线 */
.semi-input-group > *:not(:last-child)::after {
  display: none;
}

/* 合并相邻边框 */
.semi-input-group > *:not(:last-child) .semi-input-wrapper {
  border-right-width: 0;
}
.semi-input-group > *:not(:first-child) .semi-input-wrapper {
  border-left-width: 0;
}
```

可以继续关注这个 issue，后续有进展会同步更新。
