### ISSUE TITLE
[BUG] <title> table semi-table-header 在 overflow-y 的属性下的加载抖动

### ISSUE THREAD

**Issue by manyuemeiquqi** [DouyinFE/semi-design#2527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

table

### Semi Version

latest

### Current Behavior

![20241012172226_rec_](https://github.com/user-attachments/assets/2ed69b9f-2907-458d-89f4-4e30dffc4166)

### Expected Behavior

期望 table 表格在无数据跟有数据下滚动条保持一致的样式，不出现抖动

### Environment

```markdown
- OS:
- browser:
```

**Comment by SudoUserReal** [comment]
这个问题是滚动条在内容溢出与否时出现的宽度变化导致的，在 Windows 系统上会比较明显。

可以通过 CSS 覆盖解决，推荐用 `scrollbar-gutter: stable`：

```css
.semi-table-body {
    scrollbar-gutter: stable;
}
```

这样浏览器会预留滚动条空间，无数据时也不会抖动，且不会强制显示一个不可用的滚动条。兼容性方面，Chrome 94+、Firefox 97+、Safari 17+ 都支持。

或者如果不介意无数据时显示一个灰色不可用的滚动条，也可以：

```css
.semi-table-body {
    overflow-y: scroll !important;
}
```

组件层面暂时不会默认加这个处理，因为不同业务场景对滚动条的期望可能不同，保持现有行为让用户按需覆盖会更灵活一些。
