### ISSUE TITLE
[Themes] Allow modern colour formats like oklch.

### ISSUE THREAD

**Issue by BleedingDev** [DouyinFE/semi-design#2671]
### Which Component Need Enhancement 期望新增功能的组件
- Themes

### What does the proposed API look like 期望支持的API
Same as for RGB, only allows different values.

### Feature Description 功能描述
Allow definition of themes in modern CSS formats like oklch.

### Additional information 补充说明
Tailwind recently added new colours:
https://tailwindcss.com/docs/v4-beta#modernized-p3-color-palette
oklch is widely supported:
https://caniuse.com/?search=oklch

**Comment by BleedingDev** [comment]
Usage scenario is support of better monitors with more colours. It also can provide smoother transitions because of more colours in total.

> OKLCH supports a wide gamut of colors, such as sRGB, Display P3, and even the most recent Rec2020. The Display P3 gamut has 50% more colors than the sRGB gamut.

I think this article explains it well:
https://www.smashingmagazine.com/2023/08/oklch-color-spaces-gamuts-css/

**Comment by SudoUserReal** [comment]
Thank you for raising this feature request! We fully understand the value of modern color formats like oklch — supporting wider color gamuts (Display P3, Rec2020) can definitely bring a better visual experience for users with high-end displays.

For now, here are two approaches you can use to achieve this:

### Approach 1: CSS Variable Override (Recommended)

Semi Design's color system is built on CSS variables, so you can directly override the semantic color variables in your project:

```css
/* In your global stylesheet, ensure higher priority than Semi's default styles */
body {
  /* Override primary color */
  --semi-color-primary: oklch(0.6 0.2 250);
  --semi-color-primary-hover: oklch(0.55 0.22 250);
  --semi-color-primary-active: oklch(0.5 0.24 250);
  
  /* Override success color */
  --semi-color-success: oklch(0.7 0.18 145);
  --semi-color-success-hover: oklch(0.65 0.2 145);
  
  /* Override danger color */
  --semi-color-danger: oklch(0.65 0.22 25);
  --semi-color-danger-hover: oklch(0.6 0.24 25);
  
  /* Other color variables follow the same pattern... */
}

/* Override for dark mode */
body[theme-mode="dark"] {
  --semi-color-primary: oklch(0.7 0.18 250);
  /* ... */
}
```

**Notes**:
1. Semi's default palette variables (e.g., `--semi-blue-5`) use RGB component format `r,g,b` combined with `rgba()`. If you only override semantic variables (e.g., `--semi-color-primary`), you can skip this limitation and use complete color values directly.
2. We recommend using `@supports` for graceful degradation:
   ```css
   @supports (color: oklch(0 0 0)) {
     body {
       --semi-color-primary: oklch(0.6 0.2 250);
     }
   }
   ```

### Approach 2: Custom Theme Package

If you need more comprehensive oklch support, you can modify a custom theme package:

1. Create and publish your custom theme package to npm via the [DSM Theme Platform](https://semi.design/dsm)
2. Download the theme package locally and modify the color definitions in `scss/_palette.scss` and `scss/global.scss` to oklch format
3. Re-publish the package or use the local version directly in your project

---

Regarding native oklch format support in the DSM Theme Platform: this feature is not currently in our near-term roadmap. We will discuss and evaluate this internally and share updates later. Key considerations include browser compatibility, integration with existing toolchains, and migration cost for users.

In the meantime, the two approaches above can serve as interim solutions. If you encounter any issues while implementing them, please feel free to continue the discussion!
