### ISSUE TITLE
[Theme] Allow arbitrary values

### ISSUE THREAD

**Issue by BleedingDev** [DouyinFE/semi-design#2672]
### Which Component Need Enhancement 期望新增功能的组件
- Theme
- Web Console

### What does the proposed API look like 期望支持的API
Same, just allow arbitrary values.

### Feature Description 功能描述
Fluid design works really well but can't be achieved in Semi Design without overwriting only on code side (without sync to published package).

### Additional information 补充说明
Example of fluid Typography:
https://utopia.fyi/type/calculator/
Example of fluid Spacing:
https://utopia.fyi/space/calculator/

**Comment by SudoUserReal** [comment]
Thanks for your feedback!

Regarding implementing Fluid Design in Semi Design, here are two temporary workarounds for your reference:

### Option 1: Override CSS Variables

Semi Design uses CSS variables as Design Tokens (e.g., `--semi-color-primary`, `--semi-font-size-body`). You can override these variables in your global styles to achieve fluid design:

```css
/* In your global CSS */
:root {
  /* Fluid typography example - using clamp() for responsive font sizes */
  --semi-font-size-body: clamp(14px, 1vw + 12px, 18px);
  --semi-font-size-headline: clamp(20px, 2vw + 16px, 32px);
  
  /* Fluid spacing example */
  --semi-spacing-base: clamp(8px, 0.5vw + 6px, 16px);
  
  /* Other custom token overrides... */
}
```

This approach takes effect immediately without republishing the theme package. However, please note:
- Only existing Semi CSS variables are supported; you cannot add new tokens
- You need to refer to the [Tokens documentation](https://semi.design/en-US/basic/tokens) for variable names

### Option 2: Download and Modify the Theme Package Source Code

If you need deeper customization (e.g., adding new tokens, modifying component-level styles):

1. Publish your theme package to npm via [Semi DSM](https://semi.design/dsm)
2. Download the theme package source code from npm
3. Directly edit the SCSS variable files (e.g., `scss/variables.scss`), replacing fixed values with `clamp()`/`calc()` or other fluid design values
4. Reference the modified theme package locally, or republish it to your private npm

This approach is more flexible and supports arbitrary value modifications.

---

Regarding adding arbitrary value input support in the DSM platform, this feature won't be added at this time. We will discuss and evaluate this requirement internally, and will update this Issue if there's any progress.

If you encounter any specific issues during implementation, feel free to continue the discussion.
