### ISSUE TITLE
[BUG] 工程化，设置 cssLayer 同时设置 prefixCls，样式无法生效

### ISSUE THREAD

**Issue by YyumeiZhang** [DouyinFE/semi-design#2844]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which Component

无

### Semi Version

2.80.0

### Current Behavior

cssLayer 开启的时候，如果设置了prefixCls，组件类名称是被替换掉的，则编译后的 semi 的 css 中 prefix 没有被替换

### Expected Behavior

组件名称替换正确，css 中 prefix 替换正确

### ReproducibleCode

```markdown

```

### Environment

```markdown
- OS:
- browser:
```

**Comment by SudoUserReal** [comment]
我在当前 main 分支（v2.82.1+）上对 `cssLayer + prefixCls` 组合做了完整的复现验证，结论是该问题在当前代码下无法复现，相关细节如下。

## 一、代码核对

`semi-webpack` / `semi-rspack` / `semi-vite` 三个工程化包的 theme-loader 在 `cssLayer + prefixCls` 场景下的拼装逻辑是一致的，注入顺序如下：

```ts
// packages/semi-webpack/src/semi-theme-loader.ts
finalCSS = `${animationStr}${cssVarStr}${scssVarStr}${prefixClsStr}${fileStr}${customStr}`;
if (cssLayer) {
    finalCSS = `@layer semi{${finalCSS}}`;
}
```

其中：

- `scssVarStr` = `@import "~${theme}/scss/index.scss";`，其内部 `variables.scss` 定义 `$prefix: 'semi'`（默认值）。
- `prefixClsStr` = `$prefix: '${用户的 prefixCls}';`，紧跟在 `scssVarStr` 之后，用于覆盖默认值。
- `fileStr` 是 semi-foundation/semi-ui/semi-icons 的 lib 下原始 scss 内容，里面所有选择器都通过 `#{$prefix}-xxx` 引用。

按 Sass 作用域规则，整体被包在 `@layer semi { ... }` 内时，`$prefix` 在该块内被重新赋值，块内对 `$prefix` 的引用应解析为新值。

## 二、Vite 插件实测

`packages/semi-vite/test/run.mjs` 中的 case 1 已经覆盖了本 issue 的场景：

```js
await runCase('full', {
    theme: '@douyinfe/semi-theme-default',
    prefixCls: 'qiang',
    variables: { '$font-size-small': '20px' },
    cssLayer: true
});
assert.match(cssContent, /@layer\s+semi/);
assert.match(cssContent, /\.qiang-button/);
assert.doesNotMatch(cssContent, /\.semi-button/);
assert.match(jsContent, /BASE_CLASS_PREFIX\s*=\s*["']qiang["']/);
```

执行 `npm test` 实际输出：

```
== case 1: full options (theme + prefix + variables + cssLayer) ==
CSS: @layer semi{.qiang-button{color:red;font-size:20px}.semi-base{color:red}}
All assertions passed ✓
```

CSS 中类选择器 `.qiang-button` 正确替换前缀，未保留 `.semi-button`。

## 三、Webpack 插件实测

直接调用 `@douyinfe/semi-webpack-plugin/lib/semi-theme-loader.js` 处理一个模拟的 `button.scss`（内部含 `.#{$prefix}-button { ... }`），传入 options：

```js
{ prefixCls: 'qiang', cssLayer: true, name: '@douyinfe/semi-theme-default' }
```

Loader 输出：

```scss
@layer semi{@import "~@douyinfe/semi-theme-default/scss/animation.scss";
@import "~@douyinfe/semi-theme-default/scss/global.scss";
@import "~@douyinfe/semi-theme-default/scss/index.scss";
$prefix: 'qiang';
@import './button-variables.scss';
.#{$prefix}-button { ... }
.semi-base { ... }
body:not(:not(body)){};}
```

再用 sass 编译后：

```css
@layer semi {
  .qiang-button {
    color: blue;
    font-size: 12px;
  }
  .semi-base {
    color: blue;
  }
}
```

组件选择器 `.qiang-button` 正确替换。需要说明，输出中保留的 `.semi-base` 是 loader 中刻意保留的注入标记位（见 `const shouldInject = source.includes('semi-base');`），并非真实组件类名，不会被渲染到 DOM。

## 四、Rspack 插件

`packages/semi-rspack/src/loaders/semi-theme-loader.ts` 与 webpack 版本逻辑完全一致，结论同上。

## 五、结论

在当前 main 分支（v2.82.1+）上：

1. Vite 插件单测断言通过；
2. Webpack 插件直接调用 loader + sass 编译，输出符合预期；
3. Rspack 插件代码逻辑等价，结论一致。

该 issue 描述的「cssLayer + prefixCls 同时启用时编译后 CSS 中 prefix 未被替换」**目前无法复现**。git log 中也没有针对该问题的修复 commit，推测当时可能与项目里其他工程配置叠加相关。

## 六、建议

该 issue 创建时未提供 Steps To Reproduce 与 ReproducibleCode。如果在最新版本上仍能复现，请提供最小复现仓库（建议包含 webpack / rspack / vite 配置文件、Semi 版本、构建产物 CSS 片段），便于进一步定位。如无法补充复现，建议关闭该 issue。
